name: Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t registry.cn-shanghai.aliyuncs.com/limingxinleo/sign-api:${GITHUB_REF#*/*/} .
      - name: Login Aliyun
        run: docker login registry.cn-shanghai.aliyuncs.com -u 715557344@qq.com -p ${{ secrets.ALIYUN_ACCESS_TOKEN }}
      - name: Push Image
        run: docker push registry.cn-shanghai.aliyuncs.com/limingxinleo/sign-api:${GITHUB_REF#*/*/}
